apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: webapp
  annotations:
    argocd.argoproj.io/sync-wave: "0"  
data:
  index.html: |
    <html>
    <head><title>Hello from ConfigMap</title></head>
    <body>
      <h1>Welcome to the Nginx app deployed with ArgoCD!</h1>
    </body>
    </html>
