apiVersion: batch/v1
kind: Job
metadata:
  name: presync-log
  namespace: webapp
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  template:
    spec:
      containers:
        - name: log
          image: busybox
          command: ['sh', '-c', 'echo " ArgoCD PreSync Hook executed!"']
      restartPolicy: Never
  backoffLimit: 0
